# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
#        restart: always
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - mysql
            - redis
    pgsql:
        image: 'postgres:14'
#        restart: always
        ports:
            - '${PGSQL_DB_FORWARD_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${PGSQL_DB_DATABASE}'
            POSTGRES_USER: '${PGSQL_DB_USERNAME}'
            POSTGRES_PASSWORD: '${PGSQL_DB_PASSWORD}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${PGSQL_DB_DATABASE}", "-U", "${PGSQL_DB_USERNAME}"]
            retries: 3
            timeout: 5s
    mysql:
        image: 'mysql/mysql-server:8.0'
#        restart: always
        ports:
            - '${MYSQL_DB_FORWARD_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${MYSQL_DB_DATABASE}'
            MYSQL_USER: '${MYSQL_DB_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
#        restart: always
        ports:
            - '${REDIS_FORWARD_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    swagger:
        image: 'swaggerapi/swagger-ui'
#        restart: always
        ports:
            - '${SWAGGER_PORT:-8080}:8080'
        networks:
            - sail
        volumes:
            - "./storage/app/public/docs:/docs"
        environment:
            SWAGGER_JSON: /docs/openapi.json
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
